CREATE TABLE TOOL
(
  TOOL_ID INTEGER(36) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(63) NOT NULL,
  QUANTITY INTEGER(4) NOT NULL,
  IS_REACHABLE BOOLEAN
);

CREATE TABLE RESERVATION
(
    RESERVATION_ID INTEGER(36) PRIMARY KEY AUTO_INCREMENT,
    SUBJECT_NAME VARCHAR(63) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL
);