CREATE TABLE GYM_PERIOD
(
    PERIOD_ID  INTEGER(36) PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(63) NOT NULL,
    IS_ACTIVE  BOOLEAN,
    START_DATE DATE        NOT NULL,
    END_DATE   DATE        NOT NULL
);

CREATE TABLE TICKETS
(
    USER_ID   INTEGER(36),
    PERIOD_ID INTEGER(36),
    FOREIGN KEY (USER_ID) REFERENCES GYM_USER (USER_ID),
    FOREIGN KEY (PERIOD_ID) REFERENCES GYM_PERIOD (PERIOD_ID)
);
