CREATE TABLE TRAINING
(
    TRAINING_ID      INTEGER(36) PRIMARY KEY AUTO_INCREMENT,
    NAME             VARCHAR(63) NOT NULL,
    MAX_PARTICIPANTS INTEGER(4)  NOT NULL,
    DESCRIPTION      VARCHAR(511),
    START_DATE       TIMESTAMP   NOT NULL,
    END_DATE         TIMESTAMP   NOT NULL
);

CREATE TABLE TRAINING_PARTICIPANTS
(
    PARTICIPANT_ID     INTEGER(36),
    TRAINING_ID INTEGER(36),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES GYM_USER (USER_ID),
    FOREIGN KEY (TRAINING_ID) REFERENCES TRAINING (TRAINING_ID)
);
