CREATE TABLE SUBSCRIPTION
(
    NAME VARCHAR(63) NOT NULL PRIMARY KEY
);

CREATE TABLE USER_SUBSCRIPTIONS
(
    USER_ID           INTEGER(36),
    SUBSCRIPTION_NAME VARCHAR(63),
    FOREIGN KEY (USER_ID) REFERENCES GYM_USER (USER_ID),
    FOREIGN KEY (SUBSCRIPTION_NAME) REFERENCES SUBSCRIPTION (NAME)
);

INSERT INTO SUBSCRIPTION(NAME) VALUES ('ON_NEW_ARTICLES');
INSERT INTO SUBSCRIPTION(NAME) VALUES ('ON_NEW_TRAININGS');
INSERT INTO SUBSCRIPTION(NAME) VALUES ('ON_SUBSCRIBED_TRAININGS');
