CREATE TABLE GYM_USER
(
  USER_ID INTEGER(36) PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(64) UNIQUE NOT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL
)